"use strict";(self.webpackChunkluna_ui=self.webpackChunkluna_ui||[]).push([[461],{87898:function(b,v,n){n.r(v),n.d(v,{demos:function(){return s}});var x=n(90228),a=n.n(x),j=n(87999),i=n.n(j),u=n(75271),h=n(64397),c=n(43132),E=n(74897),P=n(76044),s={"src-button-demo-0":{component:u.memo(u.lazy(i()(a()().mark(function t(){var d,r,l,o;return a()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,Promise.resolve().then(n.bind(n,43132));case 2:return d=e.sent,r=d.Button,e.next=6,Promise.resolve().then(n.bind(n,74897));case 6:return l=e.sent,o=l.FaBeer,e.abrupt("return",{default:function(){return u.createElement("div",{style:{display:"flex",gap:"10px",padding:20}},u.createElement(r,{type:"primary"},"button"),u.createElement(r,{type:"warning"},"button"),u.createElement(r,{type:"danger"},"button"),u.createElement(r,{color:"red"},"button"))}});case 9:case"end":return e.stop()}},t)})))),asset:{type:"BLOCK",id:"src-button-demo-0",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Button } from 'luna-ui';\r
import { FaBeer } from 'react-icons/fa';\r
\r
export default () => (\r
  <div style={{ display: 'flex', gap: '10px', padding: 20 }}>\r
    <Button type="primary">button</Button>\r
    <Button type="warning">button</Button>\r
    <Button type="danger">button</Button>\r
    {/* \u9ED8\u8BA4\u4E3A default */}\r
    <Button color="red">button</Button>\r
  </div>\r
);`},"luna-ui":{type:"NPM",value:"0.0.1"},undefined:{type:"NPM"}},entry:"index.jsx"},context:{"luna-ui":c,"react-icons/fa":E},renderOpts:{compile:function(){var t=i()(a()().mark(function r(){var l,o=arguments;return a()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(977).then(n.bind(n,56977));case 2:return e.abrupt("return",(l=e.sent).default.apply(l,o));case 3:case"end":return e.stop()}},r)}));function d(){return t.apply(this,arguments)}return d}()}},"src-button-demo-1":{component:u.memo(u.lazy(i()(a()().mark(function t(){var d,r;return a()().wrap(function(o){for(;;)switch(o.prev=o.next){case 0:return o.next=2,Promise.resolve().then(n.bind(n,43132));case 2:return d=o.sent,r=d.Button,o.abrupt("return",{default:function(){return u.createElement("div",{style:{padding:20}},u.createElement(r,{type:"primary",disabled:!0},"button"))}});case 5:case"end":return o.stop()}},t)})))),asset:{type:"BLOCK",id:"src-button-demo-1",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Button } from 'luna-ui';\r
\r
export default () => (\r
  <div style={{ padding: 20 }}>\r
    <Button type="primary" disabled={true}>\r
      button\r
    </Button>\r
  </div>\r
);`},"luna-ui":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{"luna-ui":c},renderOpts:{compile:function(){var t=i()(a()().mark(function r(){var l,o=arguments;return a()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(977).then(n.bind(n,56977));case 2:return e.abrupt("return",(l=e.sent).default.apply(l,o));case 3:case"end":return e.stop()}},r)}));function d(){return t.apply(this,arguments)}return d}()}},"src-button-demo-2":{component:u.memo(u.lazy(i()(a()().mark(function t(){var d,r,l,o;return a()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,Promise.resolve().then(n.bind(n,43132));case 2:return d=e.sent,r=d.Button,e.next=6,Promise.resolve().then(n.bind(n,76044));case 6:return l=e.sent,o=l.AiOutlineSearch,e.abrupt("return",{default:function(){return u.createElement("div",{style:{display:"flex",gap:"10px",padding:20}},u.createElement(r,{type:"primary",icon:u.createElement(o,null)},"\u641C\u7D22"),u.createElement(r,{type:"primary",iconPosition:"right",icon:u.createElement(o,null),textColor:"#000"},"\u641C\u7D22"))}});case 9:case"end":return e.stop()}},t)})))),asset:{type:"BLOCK",id:"src-button-demo-2",refAtomIds:[],dependencies:{"index.jsx":{type:"FILE",value:`import { Button } from 'luna-ui';\r
import { AiOutlineSearch } from 'react-icons/ai';\r
\r
export default () => (\r
  <div style={{ display: 'flex', gap: '10px', padding: 20 }}>\r
    {/* \u9ED8\u8BA4\u6587\u5B57\u65B9\u5411\u5728\u6587\u5B57\u5DE6\u4FA7 \u56FE\u6807\u989C\u8272\u4E0E\u5B57\u4F53\u4E00\u81F4*/}\r
    <Button type="primary" icon={<AiOutlineSearch />}>\r
      \u641C\u7D22\r
    </Button>\r
    <Button\r
      type="primary"\r
      iconPosition="right"\r
      icon={<AiOutlineSearch />}\r
      textColor="#000"\r
    >\r
      \u641C\u7D22\r
    </Button>\r
  </div>\r
);`},"luna-ui":{type:"NPM",value:"0.0.1"},undefined:{type:"NPM"}},entry:"index.jsx"},context:{"luna-ui":c,"react-icons/ai":P},renderOpts:{compile:function(){var t=i()(a()().mark(function r(){var l,o=arguments;return a()().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return e.next=2,n.e(977).then(n.bind(n,56977));case 2:return e.abrupt("return",(l=e.sent).default.apply(l,o));case 3:case"end":return e.stop()}},r)}));function d(){return t.apply(this,arguments)}return d}()}}}},43132:function(b,v,n){n.r(v),n.d(v,{Button:function(){return P},Icon:function(){return h}});var x=n(26068),a=n.n(x),j=n(75271),i=n(52676),u=function(t){var d=t.size,r=d===void 0?12:d,l=t.color,o=l===void 0?"#000000":l,p=t.onClick,e=t.className,m=e===void 0?"":e,I=t.icon;return(0,i.jsx)("span",{onClick:p,className:"icon-container ".concat(m),style:{display:"inline-flex",width:r,height:r,color:o},children:I})},h=u,c=function(s){return s.PRIMARY="primary",s.WARNING="warning",s.DANGER="danger",s.DEFAULT="default",s}(c||{}),E=function(t){var d,r,l,o=t.classNames,p=o===void 0?"":o,e=t.width,m=t.height,I=t.type,R=t.color,D=t.disabled,L=D===void 0?!1:D,W=t.label,f=t.icon,O=t.iconPosition,M=O===void 0?"left":O,A=t.size,C=A===void 0?18:A,$=t.textColor,g=$===void 0?"#fff":$,N=t.onClick,S=t.children,y={width:e+"px",height:m+"px"},B=function(){switch(I){case c.PRIMARY:return a()(a()({},y),{},{backgroundColor:"#1890ff",color:"#fff"});case c.WARNING:return a()(a()({},y),{},{backgroundColor:"#faad14",color:"#fff"});case c.DANGER:return a()(a()({},y),{},{backgroundColor:"#ff4d4f",color:"#fff"});case c.DEFAULT:return a()(a()({},y),{},{backgroundColor:"#d9d9d9",color:"#000"})}};return(0,i.jsx)("button",{className:"button ".concat(I," ").concat(p),style:I?B():a()(a()({},y),{},{backgroundColor:R,color:g}),disabled:L,onClick:N,children:(0,i.jsxs)("div",{children:[f&&M==="left"&&(0,i.jsx)(h,{icon:f,color:g||((d=B())===null||d===void 0?void 0:d.color),size:C}),(0,i.jsx)("span",{style:{fontSize:C,margin:f?"0 8px":"0",color:g||((r=B())===null||r===void 0?void 0:r.color)},children:W||S}),f&&M==="right"&&(0,i.jsx)(h,{icon:f,color:g||((l=B())===null||l===void 0?void 0:l.color),size:C})]})})},P=E},80634:function(b,v,n){n.r(v),n.d(v,{texts:function(){return a}});var x=n(64397);const a=[{value:"\u4E00\u4E2A\u53EF\u590D\u7528\u7684 \u6309\u94AE \u7EC4\u4EF6\uFF0C\u652F\u6301\u81EA\u5B9A\u4E49\u5C3A\u5BF8\uFF0C\u989C\u8272\uFF0C\u70B9\u51FB\u4E8B\u4EF6\u7B49\u3002",paraId:0,tocIndex:0},{value:"\u672C\u7EC4\u4EF6\u5E93 \u5EFA\u8BAE\u4F7F\u7528 react-icons \u56FE\u6807\u5E93",paraId:1,tocIndex:1},{value:`pnpm add react-icons\r
\r
\u6216\u8005\r
\r
npm install react-icons
`,paraId:2,tocIndex:2},{value:"\u53EF\u4EE5\u5728\u5DE6\u4FA7\u6216\u53F3\u4FA7\u663E\u793A\u56FE\u6807\uFF0C\u9ED8\u8BA4\u4E3A\u5DE6\u4FA7\u3002",paraId:3,tocIndex:6},{value:"\u56FE\u6807\u989C\u8272\u4E0E\u5B57\u4F53\u989C\u8272\u4E00\u81F4\u3002",paraId:4,tocIndex:6},{value:"\u53C2\u6570",paraId:5,tocIndex:7},{value:"\u8BF4\u660E",paraId:5,tocIndex:7},{value:"\u7C7B\u578B",paraId:5,tocIndex:7},{value:"\u9ED8\u8BA4\u503C",paraId:5,tocIndex:7},{value:"className",paraId:5,tocIndex:7},{value:"\u7528\u6237\u81EA\u5B9A\u4E49\u7684\u7C7B\u540D",paraId:5,tocIndex:7},{value:"string",paraId:5,tocIndex:7},{value:"-",paraId:5,tocIndex:7},{value:"color",paraId:5,tocIndex:7},{value:"\u6309\u94AE\u7684\u80CC\u666F\u989C\u8272",paraId:5,tocIndex:7},{value:"string",paraId:5,tocIndex:7},{value:"#000000",paraId:5,tocIndex:7},{value:"icon",paraId:5,tocIndex:7},{value:"\u7528\u6237\u4F20\u5165\u7684\u56FE\u6807\u5143\u7D20\uFF08\u5982 SVG \u6216 React \u56FE\u6807\uFF09",paraId:5,tocIndex:7},{value:"JSX.Element",paraId:5,tocIndex:7},{value:"\u5FC5\u586B",paraId:5,tocIndex:7},{value:"size",paraId:5,tocIndex:7},{value:"\u6309\u94AE\u6587\u5B57\u5C3A\u5BF8\uFF0C\u5355\u4F4D\u4E3A px",paraId:5,tocIndex:7},{value:"number",paraId:5,tocIndex:7},{value:"24",paraId:5,tocIndex:7},{value:"type",paraId:5,tocIndex:7},{value:"\u989C\u8272\u7C7B\u578B\uFF0C\u53EF\u9009\u503C\u4E3A primary\u3001warning\u3001danger\u3001default",paraId:5,tocIndex:7},{value:"string",paraId:5,tocIndex:7},{value:"default",paraId:5,tocIndex:7},{value:"iconPosition",paraId:5,tocIndex:7},{value:"\u56FE\u6807\u4F4D\u7F6E\uFF0C\u53EF\u9009\u503C\u4E3A left\u3001right",paraId:5,tocIndex:7},{value:"string",paraId:5,tocIndex:7},{value:"left",paraId:5,tocIndex:7},{value:"disabled",paraId:5,tocIndex:7},{value:"\u7981\u7528\u72B6\u6001",paraId:5,tocIndex:7},{value:"boolean",paraId:5,tocIndex:7},{value:"false",paraId:5,tocIndex:7},{value:"textColor",paraId:5,tocIndex:7},{value:"\u6587\u672C\u989C\u8272\uFF0C\u9ED8\u8BA4\u4E3A\u767D\u8272",paraId:5,tocIndex:7},{value:"string",paraId:5,tocIndex:7},{value:"#ffffff",paraId:5,tocIndex:7},{value:"\u540D\u79F0",paraId:6,tocIndex:8},{value:"\u8BF4\u660E",paraId:6,tocIndex:8},{value:"\u7C7B\u578B",paraId:6,tocIndex:8},{value:"onClick",paraId:6,tocIndex:8},{value:"\u6309\u94AE\u70B9\u51FB\u4E8B\u4EF6",paraId:6,tocIndex:8},{value:"() => void",paraId:6,tocIndex:8}]}}]);
